In [1]:
import numpy as np
import pandas as pd

In [3]:
url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names=['sepal-length','sepal-width','petal-length','petal-width','Class']
dataset=pd.read_csv(url,names=names)

In [4]:
x= dataset.iloc[:,:-1].values
y=dataset.iloc[:,4].values

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [6]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
scalar.fit(x_train)
x_train=scalar.transform(x_train)
x_test=scalar.transform(x_test)
print(x_train)
print(x_test)

[[ 0.01700484 -0.83304935  0.27706982 -0.15685141]
 [-0.22306347 -0.38071486 -0.0046961   0.24080005]
 [ 0.49714146 -0.38071486  0.38977619  0.24080005]
 [-1.06330255 -1.28538383  0.50248256  0.77100201]
 [ 0.13703899 -0.15454762  0.333423    0.50590103]
 [-0.82323424  0.9762886  -1.24446614 -1.21725531]
 [ 0.73720977  0.29778687  0.95330803  1.56630493]
 [ 0.61717561  0.52395411  1.34778032  1.83140591]
 [ 1.81751716 -0.38071486  1.51683987  0.90355249]
 [ 0.73720977  0.29778687  0.50248256  0.50590103]
 [ 1.33738054  0.07161963  0.84060166  1.56630493]
 [ 1.697483   -0.15454762  1.23507395  0.63845152]
 [-1.06330255  0.07161963 -1.18811296 -1.3498058 ]
 [-0.10302932  3.01179379 -1.18811296 -0.95215434]
 [ 0.73720977 -0.6068821   1.12236758  1.30120396]
 [-0.22306347 -0.83304935  0.333423    0.24080005]
 [-0.82323424  1.65479033 -0.96270023 -0.95215434]
 [ 0.73720977 -0.38071486  0.38977619  0.24080005]
 [ 0.73720977 -0.83304935  0.95330803  1.03610298]
 [-0.10302932 -1.28538383  0.78

In [9]:
from sklearn.neighbors import KNeighborsClassifier
knclsfr= KNeighborsClassifier(n_neighbors=12)
knclsfr.fit(x_train,y_train)
y_pred=knclsfr.predict(x_test)
print(y_pred)

['Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor']


In [10]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[ 6  0  0]
 [ 0 10  0]
 [ 0  0 14]]
